PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE MENTEES(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  FIRSTNAME CHAR(50) NOT NULL,
  LASTNAME CHAR(50) NOT NULL,
  EMAIL CHAR(200)
);
INSERT INTO "MENTEES" VALUES(1,'Firstname','Lastname',NULL);
INSERT INTO "MENTEES" VALUES(2,'Test','Roberts',NULL);
INSERT INTO "MENTEES" VALUES(3,'Test','Mentee',NULL);
INSERT INTO "MENTEES" VALUES(4,'Mentee','Test',NULL);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('MENTEES',4);
COMMIT;
